services:
  app:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./secrets:/secrets
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /deploypkg
        - action: rebuild
          path: ./requirements.txt
